# Generated by Django 5.0.6 on 2024-05-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(default=1),
        ),
    ]
